[2025-05-14T02:53:24.837+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_taxi_pipeline.transform_yellow_taxi_data manual__2025-05-14T02:53:22.524591+00:00 [queued]>
[2025-05-14T02:53:24.844+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_taxi_pipeline.transform_yellow_taxi_data manual__2025-05-14T02:53:22.524591+00:00 [queued]>
[2025-05-14T02:53:24.845+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-14T02:53:24.856+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): transform_yellow_taxi_data> on 2025-05-14 02:53:22.524591+00:00
[2025-05-14T02:53:24.860+0000] {standard_task_runner.py:60} INFO - Started process 176 to run task
[2025-05-14T02:53:24.863+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_pipeline', 'transform_yellow_taxi_data', 'manual__2025-05-14T02:53:22.524591+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/taxi_ingestion_dag.py', '--cfg-path', '/tmp/tmp42dy1mgo']
[2025-05-14T02:53:24.865+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask transform_yellow_taxi_data
[2025-05-14T02:53:24.879+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-14T02:53:24.909+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_taxi_pipeline.transform_yellow_taxi_data manual__2025-05-14T02:53:22.524591+00:00 [running]> on host da6d5a8a8544
[2025-05-14T02:53:24.972+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_taxi_pipeline' AIRFLOW_CTX_TASK_ID='transform_yellow_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T02:53:22.524591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-14T02:53:22.524591+00:00'
[2025-05-14T02:53:24.974+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-14T02:53:24.975+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PYTHONPATH=/opt/*** python /opt/***/scripts/run_transform_taxi.py']
[2025-05-14T02:53:24.981+0000] {subprocess.py:86} INFO - Output:
[2025-05-14T02:53:25.016+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-14T02:53:25.017+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/run_transform_taxi.py", line 4, in <module>
[2025-05-14T02:53:25.018+0000] {subprocess.py:93} INFO -     transform_yellow_taxi_data()
[2025-05-14T02:53:25.018+0000] {subprocess.py:93} INFO -   File "/opt/***/transformations/transform_taxi.py", line 2, in transform_yellow_taxi_data
[2025-05-14T02:53:25.019+0000] {subprocess.py:93} INFO -     from pyspark.sql import SparkSession
[2025-05-14T02:53:25.019+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pyspark'
[2025-05-14T02:53:25.022+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-14T02:53:25.029+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-14T02:53:25.032+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_taxi_pipeline, task_id=transform_yellow_taxi_data, execution_date=20250514T025322, start_date=20250514T025324, end_date=20250514T025325
[2025-05-14T02:53:25.041+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task transform_yellow_taxi_data (Bash command failed. The command returned a non-zero exit code 1.; 176)
[2025-05-14T02:53:25.076+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-14T02:53:25.089+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
