[2025-05-14T03:02:28.861+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_taxi_pipeline.transform_yellow_taxi_data manual__2025-05-14T03:02:25.975039+00:00 [queued]>
[2025-05-14T03:02:28.867+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_taxi_pipeline.transform_yellow_taxi_data manual__2025-05-14T03:02:25.975039+00:00 [queued]>
[2025-05-14T03:02:28.868+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-14T03:02:28.879+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): transform_yellow_taxi_data> on 2025-05-14 03:02:25.975039+00:00
[2025-05-14T03:02:28.883+0000] {standard_task_runner.py:60} INFO - Started process 176 to run task
[2025-05-14T03:02:28.885+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_pipeline', 'transform_yellow_taxi_data', 'manual__2025-05-14T03:02:25.975039+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/taxi_ingestion_dag.py', '--cfg-path', '/tmp/tmpwqhais62']
[2025-05-14T03:02:28.887+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask transform_yellow_taxi_data
[2025-05-14T03:02:28.900+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-14T03:02:28.928+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_taxi_pipeline.transform_yellow_taxi_data manual__2025-05-14T03:02:25.975039+00:00 [running]> on host 19d149340382
[2025-05-14T03:02:28.990+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_taxi_pipeline' AIRFLOW_CTX_TASK_ID='transform_yellow_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T03:02:25.975039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-14T03:02:25.975039+00:00'
[2025-05-14T03:02:28.992+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-14T03:02:28.992+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PYTHONPATH=/opt/*** python /opt/***/scripts/run_transform_taxi.py']
[2025-05-14T03:02:28.999+0000] {subprocess.py:86} INFO - Output:
[2025-05-14T03:02:29.305+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-14T03:02:29.306+0000] {subprocess.py:93} INFO - JAVA_HOME is not set
[2025-05-14T03:02:29.397+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-14T03:02:29.398+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/run_transform_taxi.py", line 4, in <module>
[2025-05-14T03:02:29.401+0000] {subprocess.py:93} INFO -     transform_yellow_taxi_data()
[2025-05-14T03:02:29.402+0000] {subprocess.py:93} INFO -   File "/opt/***/transformations/transform_taxi.py", line 8, in transform_yellow_taxi_data
[2025-05-14T03:02:29.403+0000] {subprocess.py:93} INFO -     .getOrCreate()
[2025-05-14T03:02:29.404+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
[2025-05-14T03:02:29.404+0000] {subprocess.py:93} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-05-14T03:02:29.404+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/pyspark/context.py", line 515, in getOrCreate
[2025-05-14T03:02:29.405+0000] {subprocess.py:93} INFO -     SparkContext(conf=conf or SparkConf())
[2025-05-14T03:02:29.405+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/pyspark/context.py", line 201, in __init__
[2025-05-14T03:02:29.405+0000] {subprocess.py:93} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-05-14T03:02:29.406+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/pyspark/context.py", line 436, in _ensure_initialized
[2025-05-14T03:02:29.406+0000] {subprocess.py:93} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-05-14T03:02:29.406+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
[2025-05-14T03:02:29.406+0000] {subprocess.py:93} INFO -     raise PySparkRuntimeError(
[2025-05-14T03:02:29.407+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-05-14T03:02:29.434+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-14T03:02:29.443+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-14T03:02:29.445+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_taxi_pipeline, task_id=transform_yellow_taxi_data, execution_date=20250514T030225, start_date=20250514T030228, end_date=20250514T030229
[2025-05-14T03:02:29.456+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task transform_yellow_taxi_data (Bash command failed. The command returned a non-zero exit code 1.; 176)
[2025-05-14T03:02:29.500+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-14T03:02:29.512+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
